# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Advanced Computer Vision Meetup
tagline:          'A Jekyll theme'
description:      'Official website for the <a href="http://jekyllrb.com" target="_blank">Advanced Computer Vision Meetup</a> in Berlin'
url:              https://notanymike.github.io/
baseurl:          /AdvancedComputerVision/

author:
  name:           'Mike Woodcock'
  url:            https://twitter.com/NotAnyMike

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/NotAnyMike/AdvancedComputerVision/

plugins:          [jekyll-paginate, jekyll-gist]
